name: Build and deploy to dockhost
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "ai-survey"
jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to ghcr containers
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{env.REGISTRY}}/ychebotaev/${{env.IMAGE_NAME}}
  deploy:
    name: Deploy to dockhost
    needs: build-and-push
    runs-on: ubuntu-latest
    container:
      image: dockhost/cli
      env:
        DOCKHOST_TOKEN: ${{secrets.DOCKHOST_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push to dockhost
        run: dockhost compose apply -f dockhost.yaml
